"""add due_date and amount_paid to invoice

Revision ID: 8c6099042003
Revises: 
Create Date: 2026-02-11 13:22:11.163547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c6099042003'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('amount_paid', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'due_date')
    op.drop_column('invoices', 'amount_paid')
    # ### end Alembic commands ###
